/* Generated By:JavaCC: Do not edit this line. UcParseVisitor.java Version 5.0 */
package parser;

public interface UcParseVisitor<T>
{
  public void visit(SimpleNode node, T data);
}
/* JavaCC - OriginalChecksum=3b02316a9c81b4ab466cd41f26c113ab (do not edit this line) */
